# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-12 18:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100, verbose_name='Caption')),
                ('photo', models.ImageField(default='photos/none/default.jpg', upload_to='photos/%Y/%m/%d', verbose_name='Your Photos')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created on')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
